[2020-07-13 15:27:49,793] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10448
[2020-07-13 15:27:50,922] [base.py:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
[2020-07-13 15:27:50,922] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 6354
[2020-07-13 15:27:52,905] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /get_config/ HTTP/1.1" 302 0
[2020-07-13 15:27:53,936] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2216
[2020-07-13 15:27:54,965] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/login/css/login.css HTTP/1.1" 200 1121
[2020-07-13 15:27:55,995] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/login/img/photos/timg3.jpg HTTP/1.1" 200 13234
[2020-07-13 15:28:01,715] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2020-07-13 15:28:03,076] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10448
[2020-07-13 15:28:05,765] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /get_config/ HTTP/1.1" 200 6507
[2020-07-13 15:28:13,147] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /get_config/
Traceback (most recent call last):
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\PycharmProjects\MyPro1\login\views.py", line 131, in get_config
    res_msg = get_config_info()
  File "D:\PycharmProjects\MyPro1\login\templates\utils\getconf.py", line 79, in get_config_info
    res_dict = {**res_dict, **get_dict_all(section)}
  File "D:\PycharmProjects\MyPro1\login\templates\utils\getconf.py", line 65, in get_dict_all
    dicts = {**dicts, **getdict(title, key)}
  File "D:\PycharmProjects\MyPro1\login\templates\utils\getconf.py", line 48, in getdict
    value = config.get(title, key)
  File "D:\Programs\Python\Python37\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "D:\Programs\Python\Python37\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'HOST'
[2020-07-13 15:28:13,493] [views.py:143] [views:change_hosts] [INFO]- 请求成功！ 操作人:lazy
[2020-07-13 15:28:13,494] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /api/modify_config/ HTTP/1.1" 200 2978
[2020-07-13 15:28:13,633] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /get_config/ HTTP/1.1" 500 98535
[2020-07-13 15:29:12,913] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /get_config/ HTTP/1.1" 200 2978
[2020-07-13 15:29:13,247] [views.py:143] [views:change_hosts] [INFO]- 请求成功！ 操作人:lazy
[2020-07-13 15:29:13,247] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /api/modify_config/ HTTP/1.1" 200 2978
[2020-07-13 15:29:15,856] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /get_config/ HTTP/1.1" 200 6505
[2020-07-13 15:29:19,127] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /get_config/
Traceback (most recent call last):
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\PycharmProjects\MyPro1\login\views.py", line 131, in get_config
    res_msg = get_config_info()
  File "D:\PycharmProjects\MyPro1\login\templates\utils\getconf.py", line 79, in get_config_info
    res_dict = {**res_dict, **get_dict_all(section)}
  File "D:\PycharmProjects\MyPro1\login\templates\utils\getconf.py", line 65, in get_dict_all
    dicts = {**dicts, **getdict(title, key)}
  File "D:\PycharmProjects\MyPro1\login\templates\utils\getconf.py", line 48, in getdict
    value = config.get(title, key)
  File "D:\Programs\Python\Python37\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "D:\Programs\Python\Python37\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'webHD'
[2020-07-13 15:29:19,508] [views.py:143] [views:change_hosts] [INFO]- 请求成功！ 操作人:lazy
[2020-07-13 15:29:19,511] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /get_config/ HTTP/1.1" 500 98793
[2020-07-13 15:29:19,511] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /api/modify_config/ HTTP/1.1" 200 2978
[2020-07-13 15:29:47,205] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /get_config/ HTTP/1.1" 200 6506
[2020-07-13 15:29:55,902] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10448
[2020-07-13 15:31:15,919] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /send_code/ HTTP/1.1" 200 4204
[2020-07-13 15:32:39,164] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /send_code/ HTTP/1.1" 200 4438
[2020-07-13 15:32:48,356] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10448
[2020-07-13 16:03:51,640] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 11352
[2020-07-13 16:03:53,168] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 721
[2020-07-13 16:04:01,097] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 11352
[2020-07-13 16:04:02,618] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 721
[2020-07-13 16:07:16,541] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 11352
[2020-07-13 16:07:18,159] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 721
[2020-07-13 16:09:36,878] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 11352
[2020-07-13 16:09:38,387] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 720
[2020-07-13 17:17:10,261] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10451
[2020-07-13 17:17:12,393] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10451
[2020-07-13 17:18:15,695] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10451
[2020-07-13 18:20:38,420] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10451
[2020-07-13 18:21:29,612] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10451
[2020-07-13 18:21:31,734] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /platform/add_anchor_partner HTTP/1.1" 200 3180
[2020-07-13 18:22:41,075] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /platform/add_anchor_partner HTTP/1.1" 200 3155
